//
// Generated By:JAX-WS RI IBM 2.2.1-07/09/2014 01:53 PM(foreman)- (JAXB RI IBM 2.2.3-07/07/2014 12:56 PM(foreman)-)
//


package com.fcpy.example.jaxwsboot.client.calculator;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "CalculatorDelegate", targetNamespace = "http://service.jaxwsboot.example.fcpy.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculatorDelegate {


    /**
     * 
     * @param augend
     * @param addend
     * @return
     *     returns com.fcpy.example.jaxwsboot.client.calculator.ResponseBean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://service.jaxwsboot.example.fcpy.com/", className = "com.fcpy.example.jaxwsboot.client.calculator.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://service.jaxwsboot.example.fcpy.com/", className = "com.fcpy.example.jaxwsboot.client.calculator.AddResponse")
    @Action(input = "http://service.jaxwsboot.example.fcpy.com/CalculatorDelegate/addRequest", output = "http://service.jaxwsboot.example.fcpy.com/CalculatorDelegate/addResponse")
    public ResponseBean add(
        @WebParam(name = "augend", targetNamespace = "")
        String augend,
        @WebParam(name = "addend", targetNamespace = "")
        String addend);

    /**
     * 
     * @param subtrahend
     * @param minuend
     * @return
     *     returns com.fcpy.example.jaxwsboot.client.calculator.ResponseBean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "substract", targetNamespace = "http://service.jaxwsboot.example.fcpy.com/", className = "com.fcpy.example.jaxwsboot.client.calculator.Substract")
    @ResponseWrapper(localName = "substractResponse", targetNamespace = "http://service.jaxwsboot.example.fcpy.com/", className = "com.fcpy.example.jaxwsboot.client.calculator.SubstractResponse")
    @Action(input = "http://service.jaxwsboot.example.fcpy.com/CalculatorDelegate/substractRequest", output = "http://service.jaxwsboot.example.fcpy.com/CalculatorDelegate/substractResponse")
    public ResponseBean substract(
        @WebParam(name = "minuend", targetNamespace = "")
        String minuend,
        @WebParam(name = "subtrahend", targetNamespace = "")
        String subtrahend);

    /**
     * 
     * @param multiplier
     * @param multiplicand
     * @return
     *     returns com.fcpy.example.jaxwsboot.client.calculator.ResponseBean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "multiply", targetNamespace = "http://service.jaxwsboot.example.fcpy.com/", className = "com.fcpy.example.jaxwsboot.client.calculator.Multiply")
    @ResponseWrapper(localName = "multiplyResponse", targetNamespace = "http://service.jaxwsboot.example.fcpy.com/", className = "com.fcpy.example.jaxwsboot.client.calculator.MultiplyResponse")
    @Action(input = "http://service.jaxwsboot.example.fcpy.com/CalculatorDelegate/multiplyRequest", output = "http://service.jaxwsboot.example.fcpy.com/CalculatorDelegate/multiplyResponse")
    public ResponseBean multiply(
        @WebParam(name = "multiplier", targetNamespace = "")
        String multiplier,
        @WebParam(name = "multiplicand", targetNamespace = "")
        String multiplicand);

    /**
     * 
     * @param divisor
     * @param dividend
     * @return
     *     returns com.fcpy.example.jaxwsboot.client.calculator.ResponseBean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "divide", targetNamespace = "http://service.jaxwsboot.example.fcpy.com/", className = "com.fcpy.example.jaxwsboot.client.calculator.Divide")
    @ResponseWrapper(localName = "divideResponse", targetNamespace = "http://service.jaxwsboot.example.fcpy.com/", className = "com.fcpy.example.jaxwsboot.client.calculator.DivideResponse")
    @Action(input = "http://service.jaxwsboot.example.fcpy.com/CalculatorDelegate/divideRequest", output = "http://service.jaxwsboot.example.fcpy.com/CalculatorDelegate/divideResponse")
    public ResponseBean divide(
        @WebParam(name = "dividend", targetNamespace = "")
        String dividend,
        @WebParam(name = "divisor", targetNamespace = "")
        String divisor);

}
